In [5]:
import pandas as pd

In [31]:
pedidos = pd.read_csv("Todos pedido.csv")
pedidos["Package ID"] = pedidos["Package ID"].str.replace("\t","").
pedidos["Package ID"] = pedidos["Package ID"].str.replace(" ","")

In [32]:
pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6347 entries, 0 to 6346
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Order ID                        6347 non-null   int64
 1   Package ID                      6347 non-null   object
 2   Order Status                    6347 non-null   object
 3   Order Substatus                 6347 non-null   object
 4   Cancelation/Return Type         1695 non-null   object
 5   Normal or Pre-order             6129 non-null   object
 6   SKU ID                          6347 non-null   int64
 7   Seller SKU                      6347 non-null   object
 8   Product Name                    6347 non-null   object
 9   Variation                       6347 non-null   object
 10  Product Category                6347 non-null   object
 11  Quantity                        6347 non-null   int64
 12  Sku Quantity of return          6347 non-null   int64
 13  SKU Unit Original Price         6347 non-null   object
 14  SKU Subtotal Before Discount    6347 non-null   object
 15  SKU Platform Discount           6347 non-null   object
 16  SKU Seller Discount             6347 non-null   object
 17  SKU Subtotal After Discount     6347 non-null   object
 18  Shipping Fee After Discount     6347 non-null   object
 19  Original Shipping Fee           6347 non-null   object
 20  Shipping Fee Seller Discount    6347 non-null   object
 21  Shipping Fee Platform Discount  6347 non-null   object
 22  Payment platform discount       0 non-null      float64
 23  Order Amount                    6347 non-null   object
 24  Payment Method                  6057 non-null   object
 25  Order Refund Amount             1637 non-null   object
 26  Cancel By                       1461 non-null   object
 27  Cancel Reason                   1461 non-null   object
 28  Created Time                    6347 non-null   object
 29  Paid Time                       6347 non-null   object
 30  RTS Time                        6347 non-null   object
 31  Shipped Time                    6347 non-null   object
 32  Delivered Time                  6347 non-null   object
 33  Cancelled Time                  6347 non-null   object
 34  Fulfillment Type                6347 non-null   object
 35  Warehouse Name                  6347 non-null   object
 36  Tracking ID                     4944 non-null   float64
 37  Delivery Option Type            6347 non-null   object
 38  Delivery Option                 6347 non-null   object
 39  Weight(kg)                      6347 non-null   float64
 40  Shipping Provider Name          4944 non-null   object
 41  Buyer Username                  6331 non-null   object
 42  CPF Number                      6347 non-null   object
 43  CPF Name                        6347 non-null   object
 44  Recipient                       6347 non-null   object
 45  Phone #                         6347 non-null   object
 46  Street Name                     6347 non-null   object
 47  Street Number                   6347 non-null   object
 48  Neighborhood                    6347 non-null   object
 49  House Name or Number            6347 non-null   object
 50  City                            6347 non-null   object
 51  State                           6347 non-null   object
 52  Country                         6347 non-null   object
 53  Zipcode                         6347 non-null   object
 54  Shipping Information            6347 non-null   object
 55  Invoice Status                  4959 non-null   object
 56  Buyer Message                   6 non-null      object
 57  Seller Note                     0 non-null      float64
dtypes: float64(4), int64(4), object(50)
memory usage: 2.8+ MB

In [23]:
pedidos.head(1)

,Order ID,Package ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,...,Neighborhood,House Name or Number,City,State,Country,Zipcode,Shipping Information,Invoice Status,Buyer Message,Seller Note
0,582842497552581968,,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,São Paulo,SP,Brasil,********\t,C***** q***** q*****\r\n(+55)119******12\r\n**...,NaN,NaN,NaN

In [24]:
pedidos["Package ID"] = pedidos["Package ID"].str.replace("\t","")

In [25]:
pedidos.head(2)

,Order ID,Package ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,...,Neighborhood,House Name or Number,City,State,Country,Zipcode,Shipping Information,Invoice Status,Buyer Message,Seller Note
0,582842497552581968,,Cancelado,Cancelado,Cancel,Normal,1733928767378851190,PEBCN-BBML 12-24-12-24,Kit Pares de Meias 3D com Chocalho Menino Anti...,"1 par aleatório, 1 Pares",...,*************,****,São Paulo,SP,Brasil,********\t,C***** q***** q*****\r\n(+55)119******12\r\n**...,NaN,NaN,NaN
1,582842361247204456,1187749005812008040,Enviado,Entregue,NaN,Normal,1734385029151425910,21011-41,Chinelo Masculino Esportivo Casual Confortável,"Preto/cáqui, 41CH-39BR",...,Três Marias,casa,Porto Velho,RO,Brasil,76812565\t,Francisca Ribeiro\r\n(+55)699******98\r\nRua B...,NF-e valid,NaN,NaN